#!/usr/bin/env python3
"""Westbridge — structured content. Add projects/packages/industries here, not in layouts."""

# ---------------------------------------------------------------- conceptual framework
JOURNEY = [
    ("Get found", "Website, Google and social presence so the right customers can find you."),
    ("Capture", "Every enquiry lands somewhere owned — calls, WhatsApp, forms, Instagram."),
    ("Respond", "AI or staff answer within minutes, day or night, and never leave one hanging."),
    ("Convert", "Qualify, book, quote and record — so interest becomes an appointment."),
    ("Recover", "Chase what was missed: missed calls, quiet quotes, no-shows, cold leads."),
    ("Retain", "Reviews, rebooking and reactivation turn one job into repeat revenue."),
    ("Measure", "See which channel produced which booking, and where it still leaks."),
]

# ---------------------------------------------------------------- self-diagnosis
DIAGNOSIS = [
    dict(key="leads", title="I need more enquiries",
         short="Improve website, Google visibility and lead generation.",
         panel=dict(
             finding="You are not short of a market — you are short of being found at the moment someone is looking.",
             rows=[("Usual cause", "A website that describes the business but gives a visitor nothing to do"),
                   ("Second cause", "Little or no presence where people actually search — Google, Maps and social"),
                   ("What we would look at", "Website conversion, Google Business Profile, local search visibility, landing pages"),
                   ("Typical first fix", "A conversion-led page with one clear action, plus a working local presence")],
             system="Conversion website + local visibility + lead capture + analytics",
             link="/solutions/#get-found", label="See Get found")),
    dict(key="cold", title="I get enquiries but leads go cold",
         short="Improve instant response, CRM and automated follow-up.",
         panel=dict(
             finding="You are generating interest and losing it in the gap between the enquiry and the follow-up.",
             rows=[("Usual cause", "Enquiries sit in a personal inbox or WhatsApp until someone gets to them"),
                   ("Second cause", "No follow-up after a quote — the customer simply drifts"),
                   ("What we would look at", "Response time, where enquiries land, whether anything is chased"),
                   ("Typical first fix", "Instant acknowledgement on every channel and a scheduled follow-up on quotes")],
             system="CRM + instant lead notification + WhatsApp automation + follow-up sequences",
             link="/solutions/#convert-more", label="See Convert more")),
    dict(key="missed", title="We miss calls or messages",
         short="Implement AI reception, missed-call recovery and 24/7 response.",
         panel=dict(
             finding="Enquiries are arriving when nobody can pick up, and they are not coming back.",
             rows=[("Usual cause", "Staff busy with customers in front of them, or the business is closed"),
                   ("Second cause", "Missed calls that are never returned once the rush ends"),
                   ("What we would look at", "Call and message volumes by hour, and what happens after hours"),
                   ("Typical first fix", "An AI receptionist that answers, qualifies and books — with human handover")],
             system="AI receptionist + AI WhatsApp assistant + missed-call recovery + booking",
             link="/solutions/#never-miss", label="See Never miss a customer")),
    dict(key="admin", title="My team wastes time on repetitive work",
         short="Automate bookings, reminders, FAQs, reviews and admin.",
         panel=dict(
             finding="Skilled people are doing work that does not need them, and the busywork is crowding out the work that does.",
             rows=[("Usual cause", "Reminders, confirmations and repeated questions handled manually"),
                   ("Second cause", "Review requests, quote chasing and reactivation happen only when someone remembers"),
                   ("What we would look at", "Which tasks repeat daily, and which of them can run unattended"),
                   ("Typical first fix", "Automated confirmations, reminders and review requests, then quote follow-up")],
             system="Automated reminders + review requests + quote follow-up + customer reactivation",
             link="/solutions/#automate", label="See Automate the busywork")),
]

# ---------------------------------------------------------------- solution architecture
SOLUTIONS = [
    dict(anchor="get-found", kicker="01 — Get found", title="For businesses needing more enquiries",
         outcome="Generate more qualified enquiries.",
         problem="Your website describes the business but does not turn a visitor into an enquiry.",
         features=["Conversion-led website", "Landing pages for each service",
                   "Google and local search presence", "WhatsApp enquiry button",
                   "Lead capture on every page", "Analytics and lead-source tracking"],
         link="/solutions/#get-found"),
    dict(anchor="convert-more", kicker="02 — Convert more", title="For businesses getting enquiries but losing them",
         outcome="Convert more of the leads you already generate.",
         problem="Interest arrives, then sits unanswered or unchased until the customer buys elsewhere.",
         features=["CRM and lead tracking", "Instant lead notifications",
                   "WhatsApp automation", "Lead qualification before it reaches staff",
                   "Automated follow-up sequences", "Booking and appointment reminders"],
         link="/solutions/#convert-more"),
    dict(anchor="never-miss", kicker="03 — Never miss a customer", title="For businesses struggling with calls and messages",
         outcome="Never lose a customer simply because nobody answered.",
         problem="Enquiries arrive when staff are busy or the business is closed — and do not come back.",
         features=["AI receptionist for inbound calls", "AI WhatsApp assistant",
                   "After-hours response", "Qualification and booking",
                   "Missed-call recovery", "Human escalation when it matters"],
         link="/solutions/#never-miss"),
    dict(anchor="automate", kicker="04 — Automate the busywork", title="For businesses spending too long on repetitive operations",
         outcome="Give staff more time for work that needs a human.",
         problem="Skilled people spend their day on tasks that follow the same pattern every time.",
         features=["Appointment reminders and confirmations", "FAQ handling",
                   "Review requests after service", "Quote and proposal follow-up",
                   "Customer reactivation", "Internal workflow and custom integrations"],
         link="/solutions/#automate"),
]

# ---------------------------------------------------------------- packages
PACKAGES = [
    dict(name="Westbridge Launch", for_who="For businesses needing a stronger online foundation.",
         items=["Conversion-led website", "Local discovery setup", "Landing pages",
                "WhatsApp enquiry button", "Lead capture", "Analytics"],
         outcome="Get more enquiries.", price="", feat=False),
    dict(name="Westbridge Convert", for_who="For businesses already generating enquiries.",
         items=["CRM and lead tracking", "Instant lead notifications", "WhatsApp automation",
                "Automated follow-up sequences", "Booking", "Appointment reminders"],
         outcome="Convert more of the leads you already have.", price="", feat=True),
    dict(name="Westbridge 24/7", for_who="For businesses losing customers to unanswered calls and messages.",
         items=["AI receptionist", "AI WhatsApp assistant", "After-hours support",
                "Booking and qualification", "Missed-call recovery", "Human handover"],
         outcome="Never lose a customer because nobody responded.", price="", feat=False),
    dict(name="Westbridge Growth", for_who="For businesses that want the whole system managed.",
         items=["Website and funnels", "Google and local presence", "WhatsApp and voice",
                "CRM and follow-up", "Review automation", "Customer reactivation",
                "Analytics and reporting", "Custom automation", "Continuous optimisation"],
         outcome="A managed customer acquisition and conversion system.", price="", feat=False),
]

# ---------------------------------------------------------------- how it works
STEPS = [
    ("01", "Diagnose", "Understand where enquiries arrive and where customers are being lost."),
    ("02", "Design", "Map the customer journey and recommend the highest-impact improvements first."),
    ("03", "Build", "Create and connect the website, AI, messaging, CRM and automation systems."),
    ("04", "Launch", "Test real scenarios — real calls, real messages — before switching workflows live."),
    ("05", "Improve", "Monitor performance and keep optimising as volumes and seasons change."),
]

# ---------------------------------------------------------------- portfolio
PROJECTS = [
    dict(slug="ai-receptionist", title="AI Receptionist", type="Concept Build",
         cats=["voice", "get-leads", "automation"], industry="Clinics, salons, home services",
         tags=["Voice AI", "Booking", "Lead capture"],
         summary="Answers enquiries, handles routine questions, captures leads and books appointments even when staff are unavailable.",
         problem="A potential customer calling several businesses may simply move to the next option when nobody answers. For a clinic or a service business, that call is the whole commercial event — and it is lost in the time it takes to ring out.",
         solution="An inbound voice assistant that answers every call, works out what the caller needs, answers the questions the business has approved, qualifies the enquiry, checks availability, books the appointment, sends a confirmation, writes a CRM record and triggers follow-up. Anything sensitive, uncertain or outside scope transfers to a person.",
         features=["Answers every inbound call, including after hours",
                   "Understands what the caller is asking for",
                   "Answers only approved questions, never invents",
                   "Qualifies the lead before it reaches staff",
                   "Checks availability and books the appointment",
                   "Sends confirmation and records the lead",
                   "Transfers to a human on request or uncertainty"],
         workflow=["Incoming call", "AI receptionist answers", "Understands the enquiry",
                   "Answers approved questions", "Qualifies the lead", "Checks availability",
                   "Books the appointment", "Sends confirmation", "Creates CRM record",
                   "Triggers follow-up"],
         improves=["Response speed", "After-hours availability", "Missed-enquiry recovery",
                   "Lead organisation", "Booking consistency", "Staff workload"],
         reliability=[("The AI is uncertain", "It stops and hands the call to a person rather than guessing."),
                      ("The customer asks for a person", "It transfers immediately, with the context already collected."),
                      ("The request is outside scope", "It takes a message and flags it for staff instead of improvising."),
                      ("Sensitive information appears", "Clinical, financial or identity detail is not handled by the assistant."),
                      ("Booking fails", "The lead is still captured and flagged for a callback."),
                      ("Integrations are offline", "The call is logged and queued so nothing is silently dropped.")],
         technology=["Telephony for inbound call handling", "Speech-to-text and text-to-speech",
                     "A rules and knowledge layer using only business-approved answers",
                     "Calendar integration for availability and booking", "CRM or shared inbox for lead records"],
         demo_note="Example interaction — a recorded demonstration line is being prepared.",
         demo=["Call transcript", "Booking result", "CRM record"], featured=True),
    dict(slug="whatsapp-sales-assistant", title="WhatsApp Sales Assistant", type="Concept Build",
         cats=["whatsapp", "convert-leads", "automation"], industry="Clinics, salons, real estate, coaching",
         tags=["WhatsApp", "Qualification", "Handover"],
         summary="Instant replies, FAQs, qualification, booking, follow-up and human handover — inside the chat the customer already uses.",
         problem="For most Indian local businesses, WhatsApp is the main enquiry channel and also the one most likely to be read hours later, because it sits on the owner's personal phone alongside everything else.",
         solution="A WhatsApp assistant that replies within seconds, answers the questions the business always gets asked, qualifies the enquiry with two or three questions, offers a booking, and hands over to a person the moment the conversation needs judgement.",
         features=["Replies within seconds, day or night",
                   "Answers the questions staff repeat all day",
                   "Qualifies with two or three questions",
                   "Offers available slots and books",
                   "Follows up when a conversation goes quiet",
                   "Hands over to a human on request"],
         workflow=["Enquiry arrives on WhatsApp", "Instant acknowledgement",
                   "FAQ answers from approved content", "Qualification questions",
                   "Booking offered and confirmed", "Reminder before the appointment",
                   "Human handover if needed", "Lead recorded and followed up"],
         improves=["Response speed", "Enquiry-to-booking rate", "Out-of-hours coverage",
                   "Staff time on repeated questions", "Follow-up consistency"],
         reliability=[("The assistant does not know", "It says so and asks a person to take over."),
                      ("The customer wants a human", "Immediate handover, no resistance."),
                      ("The message is sensitive", "It is routed privately to staff, not answered automatically."),
                      ("The customer opts out", "Follow-up stops immediately and permanently."),
                      ("The booking system is unreachable", "The lead is still captured for a callback.")],
         technology=["WhatsApp Business platform messaging", "Approved answer library built with the business",
                     "Rules-based qualification and routing", "Calendar and CRM integration"],
         demo_note="Example interaction — a demo WhatsApp number is being prepared.",
         demo=["WhatsApp conversation", "Booking confirmation", "Handover to staff"], featured=True),
    dict(slug="lead-recovery-engine", title="Lead Recovery Engine", type="Concept Build",
         cats=["convert-leads", "automation"], industry="Any business that quotes work",
         tags=["Follow-up", "CRM", "Reactivation"],
         summary="Automated follow-up and reactivation for leads that disappeared after the first enquiry or quote.",
         problem="Most businesses lose more revenue to silence than to competition. The quote was sent, the customer got busy, and nobody ever circled back — so nothing looks broken while the money quietly leaves.",
         solution="Every enquiry and quotation is tracked, and followed up on a schedule with short, relevant messages until the customer books, declines, or asks to stop. Follow-up stops immediately on request.",
         features=["Every quote tracked from sent to decided",
                   "Scheduled follow-up that does not rely on memory",
                   "Short, useful messages — not bulk blasts",
                   "Automatic stop when the customer books",
                   "Immediate and permanent opt-out",
                   "A view of what is still open and what is dormant"],
         workflow=["Enquiry or quote recorded", "Follow-up schedule set",
                   "Personalised messages sent on schedule", "Customer replies",
                   "Booked, declined or paused", "Dormant list reactivated later"],
         improves=["Quote-to-booking rate", "Revenue recovered from existing leads",
                   "Follow-up consistency", "Visibility of the open pipeline"],
         reliability=[("The customer asks to stop", "Follow-up ends immediately and is not re-enabled."),
                      ("The customer has already booked", "The sequence stops the moment a booking is recorded."),
                      ("The customer complains", "The contact is paused and escalated to a person.")],
         technology=["CRM or pipeline store", "Scheduled messaging across WhatsApp, SMS and email",
                     "Consent and opt-out handling", "Reporting on follow-up outcomes"],
         demo_note="Example interaction — a sample follow-up sequence is being prepared.",
         demo=["Follow-up sequence", "Pipeline view"], featured=False),
    dict(slug="appointment-noshow-system", title="Appointment & No-Show System", type="Concept Build",
         cats=["automation", "convert-leads"], industry="Clinics, salons, coaching, services",
         tags=["Reminders", "Rescheduling", "Booking"],
         summary="Confirmation, reminders, rescheduling and no-show recovery without anyone having to remember.",
         problem="Booked appointments that nobody turns up for are pure lost revenue, and the reminder that would have prevented it is a manual task that gets dropped on busy days.",
         solution="Automatic confirmation at booking, a reminder before the appointment, easy rescheduling, and a follow-up when someone does not turn up — so the slot can be refilled rather than written off.",
         features=["Confirmation at the moment of booking",
                   "Reminder before the appointment",
                   "One-tap rescheduling instead of a phone call",
                   "No-show follow-up to recover or rebook",
                   "A view of the upcoming schedule",
                   "Staff workload removed from reminding"],
         workflow=["Appointment booked", "Confirmation sent",
                   "Reminder before the visit", "Customer confirms or reschedules",
                   "No-show triggers recovery message", "Slot refilled or rebooked"],
         improves=["No-show rate", "Staff time spent reminding", "Slot utilisation",
                   "Recovery of missed appointments"],
         reliability=[("The customer reschedules repeatedly", "Escalated to staff rather than looping."),
                      ("Reminders fail to send", "Failures are logged and surfaced, not silent."),
                      ("The customer opts out", "No further reminders are sent.")],
         technology=["Booking or calendar system", "Scheduled messaging", "Rescheduling links", "No-show reporting"],
         demo_note="Example interaction — a sample reminder and reschedule flow is being prepared.",
         demo=["Reminder message", "Reschedule flow", "No-show recovery"], featured=False),
    dict(slug="local-business-growth-website", title="Local Business Growth Website", type="Concept Build",
         cats=["websites", "get-leads"], industry="Clinics, salons, venues, services",
         tags=["Website", "Conversion", "Analytics"],
         summary="A conversion-led website built to produce enquiries rather than simply describe the business.",
         problem="Many local business websites are acceptable to look at and produce almost nothing, because a visitor is never given a single clear next step at the moment they are interested.",
         solution="A site built around one action per page, with the enquiry path visible throughout, WhatsApp and booking where customers actually are, and analytics that show which pages produce enquiries rather than just which get visited.",
         features=["One clear action on every page",
                   "Enquiry path always reachable",
                   "WhatsApp and click-to-call built in",
                   "Local search and Google presence foundation",
                   "Fast on a mobile connection",
                   "Lead-source tracking, not just page views"],
         workflow=["Visitor arrives from search or social", "Understands the offer quickly",
                   "Enquiry path is obvious", "Enquiry captured",
                   "Instant acknowledgement", "Booked and recorded"],
         improves=["Visitor-to-enquiry rate", "Enquiry quality", "Mobile experience",
                   "Understanding of which channel produces business"],
         reliability=[("Forms fail", "Enquiries fall back to WhatsApp or email rather than disappearing."),
                      ("Analytics blocked", "The site still works; measurement degrades gracefully."),
                      ("The site is slow on mobile", "Treated as a defect, not an acceptable cost.")],
         technology=["Static, fast-loading pages", "Semantic HTML and structured data",
                     "Form handling to email or CRM", "Privacy-conscious analytics"],
         demo_note="Example — the Westbridge site itself is built on this approach.",
         demo=["Homepage", "Enquiry funnel", "Analytics view"], featured=False),
    dict(slug="review-generation-system", title="Review Generation System", type="Concept Build",
         cats=["automation", "retain"], industry="Clinics, salons, restaurants, services",
         tags=["Reviews", "Google", "Retention"],
         summary="A post-service workflow that asks satisfied customers for a review at the right moment.",
         problem="Satisfied customers are rarely asked, so a good business's public rating reflects who happened to remember to post rather than the quality of the work.",
         solution="A request sent after service is complete — not in a bulk email — with a single link, routed to the business's Google listing. Unhappy customers are given a direct route to the business first.",
         features=["Request triggered by completed service",
                   "One link, no account or app required",
                   "Sent by WhatsApp or SMS where customers actually read",
                   "Private feedback route for anyone unhappy",
                   "Monitoring of new reviews",
                   "Drafted responses for staff to review"],
         workflow=["Service completed", "Customer marked as served",
                   "Review request sent", "Customer leaves a review or private feedback",
                   "New review monitored", "Response drafted for approval"],
         improves=["Volume of public reviews", "Average rating over time",
                   "Recovery of unhappy customers", "Staff time on asking"],
         reliability=[("The customer is unhappy", "They are routed to private feedback rather than a public post."),
                      ("The customer ignores it", "One reminder only, then stop."),
                      ("A negative review appears", "It is surfaced immediately for a human to handle.")],
         technology=["Trigger from booking or job completion", "Messaging channel",
                     "Google review link handling", "Review monitoring and response drafting"],
         demo_note="Example interaction — a sample request and response flow is being prepared.",
         demo=["Request message", "Review landing", "Response draft"], featured=False),
    dict(slug="customer-reactivation-engine", title="Customer Reactivation Engine", type="Concept Build",
         cats=["automation", "retain", "convert-leads"], industry="Clinics, salons, gyms, coaching",
         tags=["Reactivation", "Segments", "Retention"],
         summary="Segmented reactivation campaigns that bring previous customers and dormant leads back.",
         problem="Past customers and old enquiries are the cheapest revenue a business has, and they are almost always left alone — because nobody has the time to work a list by hand.",
         solution="The customer and lead list is segmented by recency and value, and appropriate messages go out on a sensible cadence, with consent and opt-out respected throughout.",
         features=["Segmentation by recency, value and service",
                   "Campaigns appropriate to each segment",
                   "Channel chosen by what the customer reads",
                   "Consent and opt-out handled properly",
                   "Rebooking built into the message",
                   "Reporting on reactivated revenue"],
         workflow=["Customer list segmented", "Segment chosen for the campaign",
                   "Appropriate message sent", "Customer responds",
                   "Rebooking offered", "Outcome recorded and reported"],
         improves=["Repeat revenue", "Customer lifetime value", "Dormant-list recovery",
                   "Reliance on new-customer acquisition alone"],
         reliability=[("A customer has opted out", "They are excluded permanently."),
                      ("A message is inappropriate", "Segments and content are reviewed before sending."),
                      ("Response volume spikes", "Replies route to staff rather than being auto-answered.")],
         technology=["Customer and lead data store", "Segmentation rules",
                     "Multi-channel messaging with consent handling", "Reporting on recovered revenue"],
         demo_note="Example interaction — a sample reactivation campaign is being prepared.",
         demo=["Segment view", "Campaign message", "Recovered-booking report"], featured=False),
]

# ---------------------------------------------------------------- industries
INDUSTRIES = [
    dict(slug="dental-clinics", name="Dental Clinics",
         headline="Westbridge for dental clinics",
         intro="A dental practice loses patients in two predictable places: the call that rings while the dentist is in a patient's mouth, and the treatment plan that is quoted and never followed up.",
         pains=["Calls arriving during consultations and procedures",
                "Treatment plans quoted and then never chased",
                "Front-desk time consumed by the same questions",
                "Recalls and check-ups not systematically booked",
                "Satisfied patients never asked for a review"],
         workflow=["Patient enquiry (call, WhatsApp or form)", "AI or staff response within minutes",
                   "New or returning patient identified", "Reason for visit captured",
                   "Qualification and urgency check", "Appointment offered and booked",
                   "Confirmation sent", "Reminder before the visit",
                   "No-show recovery if they do not attend", "Post-visit review request",
                   "Recall and rebooking scheduled"],
         systems=["AI receptionist", "WhatsApp assistant", "Treatment-plan follow-up",
                  "Appointment reminders", "Review generation", "Recall automation"]),
    dict(slug="medical-clinics", name="Medical & Specialty Clinics",
         headline="Westbridge for medical and specialty clinics",
         intro="Specialty clinics attract high-intent enquiries worth a great deal per patient, and lose them in the hours between the enquiry and the first reply.",
         pains=["Enquiries arriving after clinic hours",
                "High-value procedures lost to slow first response",
                "Referral and follow-up appointments not coordinated",
                "No clear view of enquiries versus bookings",
                "Patient questions repeated to staff all day"],
         workflow=["Enquiry arrives on any channel", "Immediate acknowledgement",
                   "Procedure or department identified", "Suitability questions asked",
                   "Consultation offered and booked", "Pre-visit instructions sent",
                   "Reminder before the appointment", "No-show recovery",
                   "Follow-up after the consultation", "Review request"],
         systems=["After-hours response", "AI receptionist", "Booking and reminders",
                  "Enquiry tracking", "FAQ handling", "Follow-up automation"]),
    dict(slug="salons-spas", name="Salons & Spas",
         headline="Westbridge for salons and spas",
         intro="Salon enquiries arrive on Instagram and WhatsApp, at exactly the moment staff have their hands full — and the customer books whoever replies first.",
         pains=["Messages arriving while stylists are with clients",
                "Appointments confirmed by hand with no reminder",
                "Peak-hour enquiries answered slowest",
                "Regulars not rebooked before they lapse",
                "Reviews never requested from happy clients"],
         workflow=["Enquiry on Instagram, WhatsApp or call", "Instant reply",
                   "Service and timing captured", "Stylist and slot offered",
                   "Booking confirmed", "Reminder before the appointment",
                   "No-show recovery", "Review request after the visit",
                   "Rebooking prompt before the usual lapse point"],
         systems=["WhatsApp and Instagram automation", "AI receptionist",
                  "Booking and reminders", "Review generation", "Client reactivation"]),
    dict(slug="real-estate", name="Real Estate",
         headline="Westbridge for real estate brokers and builders",
         intro="Property enquiries come in volume and go cold fast, and the value of a single conversion makes response speed disproportionately important.",
         pains=["High enquiry volume spread across portals, WhatsApp and calls",
                "Agents following up inconsistently",
                "Site visits booked and not confirmed",
                "No single view of who is genuinely interested",
                "Buyers contacting several brokers simultaneously"],
         workflow=["Enquiry from portal, site, WhatsApp or call", "Instant acknowledgement",
                   "Requirement qualified (budget, location, timeline)", "Matching properties sent",
                   "Site visit offered and booked", "Confirmation and reminder",
                   "Post-visit follow-up", "Dormant buyers reactivated",
                   "Referral request after completion"],
         systems=["Lead qualification", "CRM and pipeline", "WhatsApp automation",
                  "Site-visit booking and reminders", "Dormant lead reactivation"]),
    dict(slug="hotels-hospitality", name="Hotels, Venues & Hospitality",
         headline="Westbridge for hotels, venues and banquet halls",
         intro="Room and event enquiries arrive at all hours and are frequently worth lakhs, yet many venues answer only during office hours and quote without ever following up.",
         pains=["Event enquiries arriving in the evening and answered next morning",
                "Availability checked manually rather than answered instantly",
                "Quotes sent and never chased",
                "Heavy reliance on commission-charging portals",
                "Enquiries split across calls, WhatsApp and walk-ins"],
         workflow=["Enquiry by call, WhatsApp, form or portal", "Instant reply with availability",
                   "Event date and guest count captured", "Requirements qualified",
                   "Quote sent", "Follow-up on the quote",
                   "Site visit or tasting booked", "Confirmation and reminders",
                   "Post-event review request", "Repeat and referral follow-up"],
         systems=["After-hours response", "Availability enquiry handling",
                  "Quote follow-up", "Direct-booking enquiry capture", "Review generation"]),
    dict(slug="education-coaching", name="Education & Coaching",
         headline="Westbridge for coaching centres and academies",
         intro="A single enrolled student is worth a full course fee, and admission enquiries arrive by phone while staff are teaching — so the missed-call rate directly reduces intake.",
         pains=["Calls missed because staff are teaching",
                "Entrance-test and scholarship registrants not worked afterwards",
                "No record of who enquired, visited, tested or joined",
                "Batches identified as underfilled too late",
                "Parents left waiting for a callback"],
         workflow=["Admission enquiry (call, WhatsApp or form)", "Instant acknowledgement",
                   "Course and student level captured", "Parent questions answered",
                   "Campus visit or demo class booked", "Confirmation and reminder",
                   "Post-visit follow-up", "Non-joiners followed up",
                   "Fee and batch information sent", "Enrolment confirmed"],
         systems=["AI receptionist", "Admission enquiry capture", "Test-registrant follow-up",
                  "Visit booking and reminders", "Batch-fill reporting"]),
]
